micronaut:
  application:
    name: demo
  server:
    port: 9999
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: localhost:29092
  consumers:
    mygroup:
      value:
        serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    schema:
      registry:
        url: "http://localhost:8081"
elasticsearch:
  httpHosts: "http://localhost:9200,http://127.0.0.2:9200"
